---
# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Europe/London

# jekyll-seo-tag settings
title: "Bree² Tech - Tech Insights and Solutions"
tagline: Modern day Alchemist. Turning bits and bytes into gold
description: >-
  Learn, explore, and innovate with Sr. Dan, a modern-day alchemist transforming technology. Insights and solutions on tech, Linux, cloud, cybersecurity, and more.
keywords: ["Tech Blogs", "Sr. Dan", "Coding", "Jekyll", "Alchemist", "Technology Insights", "Cybersecurity", "Cloud", "AWS", "Azure", "GCP", "Oracle", "Linux", "Windows"]

# Fill in the protocol & hostname for your site. Do not end with a slash.
url: "https://breesquared.com"

github:
  username: sto0ka

social:
  name: Sr. Dan
  email: s.tomljanovic2@gmail.com
  links:
    - https://github.com/sto0ka

webmaster_verifications:
  google: google-site-verification=KhswfUSClHzaQkbXClmW3HllcJKjhaIg-rowT3z20YY
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Web Analytics Settings
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Page views settings
pageviews:
  provider:

# Prefer color scheme setting.
theme_mode: dark

# CDN endpoint for media
cdn:

# Sidebar avatar
avatar: /assets/img.jpg

# Site-wide social preview image (optional)
social_preview_image:

# Global TOC in posts
toc: true

# Comments (fixed)
comments:
  provider: giscus    # [disqus | utterances | giscus]
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo: sto0ka/blog
    repo_id: R_kgDONPl-yA
    category: General
    category_id: DIC_kwDONPl-yM4Cksi6
    mapping: pathname
    strict: 1
    input_position: top
    lang: en
    reactions_enabled: 1

# Self-hosted static assets (optional)
assets:
  self_host:
    enabled:
    env:

# PWA
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      # - "/example"

paginate: 10

# Base URL of your site (empty string for root)
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

plugins:
  - jekyll-sitemap

# Load custom JS globally
scripts:
  - /assets/js/mermaid.js
